const menuData = [
    // Juice
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Lemon", nameAr: "ليمون", price: "0.400 / 0.600" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Lemon Mint", nameAr: "ليمون نعناع", price: "0.500 / 0.700" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Lemon Soda", nameAr: "صودا الليمون", price: "0.500" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Orange", nameAr: "البرتقالي", price: "0.600 / 0.800" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Mango", nameAr: "مانجو", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Sweet Melon", nameAr: "سويت ميلون", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Papaya", nameAr: "بابايا", price: "0.700 / 0.900" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Strawberry", nameAr: "فراولة", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Pineapple", nameAr: "أناناس", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Pomegranate", nameAr: "رمان", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Water Melon", nameAr: "بطيخ", price: "0.700 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Grape", nameAr: "عنب", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Kiwi", nameAr: "كيوي", price: "0.800 / 1.000" },
    { categoryEn: "Juice", categoryAr: "عصير", nameEn: "Mojitos", nameAr: "موهيتوس", price: "1.000 / 1.200" },

    // Hot Drinks
    { categoryEn: "Hot Drinks", categoryAr: "المشروبات الساخنة", nameEn: "Tea", nameAr: "شاي", price: "0.100 / 0.200" },
    { categoryEn: "Hot Drinks", categoryAr: "المشروبات الساخنة", nameEn: "Samovar Tea", nameAr: "شاي ساموفار", price: "0.150 / 0.300" },
    { categoryEn: "Hot Drinks", categoryAr: "المشروبات الساخنة", nameEn: "Coffee", nameAr: "قهوة", price: "0.200 / 0.400" },
    { categoryEn: "Hot Drinks", categoryAr: "المشروبات الساخنة", nameEn: "Horlicks", nameAr: "الهورليكس", price: "0.200 / 0.400" },
    { categoryEn: "Hot Drinks", categoryAr: "المشروبات الساخنة", nameEn: "Boost", nameAr: "يعزز", price: "0.200 / 0.400" },

    // Rice Items (Using provided prices, assuming small/large if two, or just one)
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Ghee Rice", nameAr: "أرز سمن", price: "0.600" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Kerala Meals", nameAr: "وجبات كيرالا", price: "1.000" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Tely Special Kerala Meal", nameAr: "وجبة تيلي الخاصة من كيرالا", price: "1.200" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Egg Biriyani", nameAr: "بيض برياني", price: "1.000" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Chicken Dum Biriyani", nameAr: "برياني دوم دجاج", price: "1.200" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Beef Dum Biriyani", nameAr: "لحم دوم برياني", price: "1.500" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Mutton Dum Biriyani", nameAr: "موتون دوم برياني", price: "1.600" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "King Fish Dum Biriyani", nameAr: "سمك كينج فيش دوم برياني", price: "1.600" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Prawns Dum Biriyani", nameAr: "قريدس دوم برياني", price: "1.600" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Quail Dum Biriyani", nameAr: "طائر دوم برياني", price: "1.500" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Camel Dum Biriyani", nameAr: "جمل دوم برياني", price: "1.600" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Fried Rice Vegetable", nameAr: "أرز مقلي خضار", price: "1.200" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Fried Rice Egg", nameAr: "أرز مقلي بيض", price: "1.200" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Fried Rice Chicken", nameAr: "أرز مقلي دجاج", price: "1.400" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Mixed Fried Rice", nameAr: "أرز مقلي مشكل", price: "1.700" },
    { categoryEn: "Rice Items", categoryAr: "عنصر الأرز", nameEn: "Vegetable Biriyani", nameAr: "برياني خضار", price: "1.200" },

    // Evening Snack
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Cutlet", nameAr: "كوفة", price: "0.200" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Irachi Pathil", nameAr: "ايريشي باتيل", price: "0.200" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Payam Pori", nameAr: "بايام بوري", price: "0.150" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Payam Nirachathu", nameAr: "بايام نيراتشو", price: "0.250" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Bread Pocket", nameAr: "جيب الخبز", price: "0.300" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Atti Pathil", nameAr: "عطا فتيلي", price: "0.250" },
    { categoryEn: "Evening Snack", categoryAr: "مساء سناكس", nameEn: "Tely Vegetable Samosa", nameAr: "ساموزا نباتية تيلي", price: "0.100" },

    // Bread Items
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Kerala Parotta", nameAr: "كيرالا باروتا", price: "0.075" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Wheat Parotta", nameAr: "باروتا القمح", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Wheat Rotti", nameAr: "روتي القمح", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Mullapu Parotta", nameAr: "مولابو بورتا", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Nool Parotta", nameAr: "نول بورتا", price: "0.150" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Idiyappam", nameAr: "أيدييبم", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Poori", nameAr: "بوري", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Appam", nameAr: "أيام", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Ari Dosa", nameAr: "أري دوسا", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Nei Pathal", nameAr: "ني باثال", price: "0.150" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Ari Orotti", nameAr: "أري أوروتي", price: "0.100" },
    { categoryEn: "Bread Items", categoryAr: "صنف الخبز", nameEn: "Putt", nameAr: "بوت", price: "0.300" },

    // Tely Special
    { categoryEn: "Tely Special", categoryAr: "خاص تيلي", nameEn: "Koth Parotta (Beef/Chicken)", nameAr: "كوثو بورتا (لحم/دجاج)", price: "1.500" },
    { categoryEn: "Tely Special", categoryAr: "خاص تيلي", nameEn: "Putt Biriyani (Beef/Chicken)", nameAr: "بوت برياني (لحم/دجاج)", price: "1.500" },
    { categoryEn: "Tely Special", categoryAr: "خاص تيلي", nameEn: "Kappa Biriyani (Beef/Chicken)", nameAr: "كابا برياني (لحم/دجاج)", price: "1.500" },
    { categoryEn: "Tely Special", categoryAr: "خاص تيلي", nameEn: "Haka Noodles", nameAr: "هاكا نودلز", price: "1.500" },
    { categoryEn: "Tely Special", categoryAr: "خاص تيلي", nameEn: "Kizhi Parotta", nameAr: "كيزي باروتا", price: "1.500" },

    // Vegetable Curry (partial list from image view)
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Kadala", nameAr: "كادالا", price: "0.400 / 0.700" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Greenpeas", nameAr: "جرينبيس", price: "0.400 / 0.700" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Cherupayar", nameAr: "شيروبايار", price: "0.400 / 0.700" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Baaji", nameAr: "باجي", price: "0.400 / 0.700" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Dal Curry", nameAr: "دال سالونة", price: "0.400 / 0.700" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Vegetable Kuruma", nameAr: "خضار كوروما", price: "0.500 / 0.800" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Vegetable Stew", nameAr: "خضار ستيو", price: "0.500 / 0.800" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Gopi Chilli", nameAr: "جوبي تشيلي", price: "1.200 / 1.800" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Gopi Manjooriyan", nameAr: "جوبي مانجوريان", price: "1.200 / 1.800" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Chilli Vegetable", nameAr: "خضار فلفل", price: "1.000 / 1.300" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Tomato Fry", nameAr: "طماطم مقلي", price: "0.800" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Kadai Paneer", nameAr: "كادي بانير", price: "1.300" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Paneer Butter Masala", nameAr: "بانير زبدة ماسالا", price: "1.300" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Chilli Paneer", nameAr: "تشيلي بانير", price: "1.300" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Mashroom Chilli", nameAr: "مشروم تشيلي", price: "1.200" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Malai Kofta", nameAr: "مالاي كفتا", price: "1.200" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Palak Paneer", nameAr: "فليك بانير", price: "1.400" },
    { categoryEn: "Vegetable Curry", categoryAr: "كاري الخضار", nameEn: "Jal Freeze", nameAr: "تجميد جال", price: "1.200" },

    // Chicken Items
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Curry", nameAr: "دجاج صالونة", price: "1.000" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Varatharacha", nameAr: "فرشات دجاج", price: "1.200" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Kashmiri", nameAr: "دجاج كشميري", price: "1.200" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Kuruma", nameAr: "دجاج كوروما", price: "1.200" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Stew", nameAr: "دجاج ستيو", price: "1.200" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Butter Chicken", nameAr: "دجاج بوتر", price: "1.200 / 1.800" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken 65", nameAr: "دجاج 65", price: "1.200 / 1.800" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Fry", nameAr: "دجاج مقلي", price: "1.200 / 1.800" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Tely Special", nameAr: "شيكن تيلي خاص", price: "1.200 / 1.800" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Tely Special Full Chicken Fry", nameAr: "تيلي سبيشل دجاج كامل مقلي", price: "3.000" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chicken Manjooriyan", nameAr: "دجاج مانجوريان", price: "1.400 / 2.000" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Kadai Chicken", nameAr: "كاداي دجاج", price: "1.400 / 2.000" },
    { categoryEn: "Chicken Items", categoryAr: "دجاج أحاج", nameEn: "Chilli Chicken", nameAr: "دجاج حار", price: "1.400 / 2.000" },

    // Beef Items
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Curry", nameAr: "لحم صالونة", price: "1.000" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Stew", nameAr: "لحم ستيو", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Mapas", nameAr: "لحم ماباس", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Kunjachan", nameAr: "لحم كونجاتشان", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Kuruma", nameAr: "لحم كورما", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Fry", nameAr: "لحم مقلي", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Dry Fry", nameAr: "جفلي لحم بكر", price: "1.300 / 1.800" },
    { categoryEn: "Beef Items", categoryAr: "لحم أغراض", nameEn: "Beef Tely Special", nameAr: "لحم تيلي خاص", price: "1.300 / 1.800" },

    // Soups
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Manchows", nameAr: "مانشو", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Hot 'N' Sour", nameAr: "حار و حامض", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Sweet Corn", nameAr: "ذرة حلوه", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Lemon Corinder", nameAr: "كزبرة الليمون", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Palak Butter", nameAr: "زبدة البلاك", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Vegetable Clear Soup", nameAr: "شوربة الخضار النقية", price: "0.800 / 1.000" },
    { categoryEn: "Soups", categoryAr: "شوربات", nameEn: "Cream of Tomato", nameAr: "كريم طماطم", price: "0.800 / 1.000" },
];
